#!/bin/sh -e
# vim:se tw=78 ai ts=2 sts=2 et:
# ext4fs label
LABEL="backup"
USERNAME=$(id -un)
# Backup should be in different hardware
export RESTIC_REPOSITORY=/media/$USERNAME/$LABEL/restic.repo
# No (real) password used since local
export RESTIC_PASSWORD=secret_password

# Sanity check
if [ ! -d /media/$USERNAME/$LABEL ]; then
  echo "Please mount /media/$USERNAME/$LABEL"
  exit
fi

if [ -n "$1" -a -z "${1%%b*}" ]; then
  # start with "b"
  # Backup with reasonable exclude
  restic backup -x \
    -e ~/.cache \
    -e ~/Downloads \
    -e ~/Music \
    -e ~/Pictures \
    -e ~/Videos \
    ~/
elif [ -n "$1" -a -z "${1%%m*}" ]; then
  # start with "m"
  echo "To unmount, type ^C to quit"
  mkdir -p ~/mnt
  restic mount ~/mnt
else
  echo "Syntax:"
  echo "  hal bkup b[ackup]"
  echo "  hal bkup m[ount]"
fi

