#!/bin/sh -e
# vim:se tw=78 ai ts=2 sts=2 sw=2 et:
##############################################################################
# Copyright (C) Osamu Aoki <osamu@debian.org>
# License: GPL 2+
##############################################################################
# fd=9 not used elsewhere in this script.
exec 9< "$0"
if ! flock --nonblock 9 ; then
  echo "${0##*/} already running.  Try later" >&2
  exit 2
fi
# Verbose level, 0 through 3
VERBOSE_LEVEL="1"
# 0     Quiet           Print fatal errors only
# 1     Default         Print errors and warnings only
# 2     Verbose         Show equivalent shell commands being executed
# 3     Debug mode      Everything
#############################################################################
# BACKUP ROOT DIRECTORY
#############################################################################

# SOURCE BTRFS path
BTRFS_SRC="/home"
# SNAPSHOT BTRFS path (RO)
BTRFS_SNAP="$HOME/snap"

mkdir -p "$BTRFS_SNAP" >/dev/null

while [ -n "$1" ] ; do
  case $1 in
    -x) set -x
      ;;
    -q) VERBOSE_LEVEL=0
      ;;
    -vv) VERBOSE_LEVEL=3
      ;;
    -v) VERBOSE_LEVEL=2
      ;;
    *) break
      ;;
  esac
  shift
done
##############################################################################
# internal functions
##############################################################################
vecho () {
if [ "$1" -le $VERBOSE_LEVEL ]; then
  shift
  echo "$*" >&2
fi
}
report () {
  if [ "$1" = "delete" ]; then
    if [ "$P_MODE" = "delete" ]; then
      echo "$2"
    elif [ "$P_MODE" = "both" ]; then
      echo "$2 --- delete --- $3"
    fi
  else
    if [ "$P_MODE" = "keep" ]; then
      echo "$2"
    elif [ "$P_MODE" = "both" ]; then
      echo "$2 +++  keep  +++ $3"
    fi
  fi
}
prune () {
# @ $NOW_EPOCH          EPOCH for current time
# @ $@                  array of ISO time of each backup (oldest first)
# @ $INDEX_NEW          Number of new timestamp index (last in list) to keep
# @ $P_AGE_HI           Use P_AGE_DEL to prune if >> P_AGE_HI
# @ $P_AGE_LO           Keep always if <<  P_AGE_LO
# @ $P_AGE_DEL          Prune delta criteria
# @ $P_AGE_FRC          Prune ratio criteria (7 means 70%)
# @ $P_MODE             output mode (delete,keep,both)
  if [ "${#}" -le "0" ]; then
    vecho 1 "W: No snapshot available"
    exit 1
  fi
  AGE_LAST=$((NOW_EPOCH-$(date +%s -d"$1")))
  FLAG=1 # update rule with AGE_LAST
  report "keep" "$1" "AGE=$AGE_LAST the oldest (0)"
  shift
  INDEX="0"
  INDEX_OLD=$((${#}-INDEX_NEW))
  for TIMESTAMP in "${@}"; do
    AGE=$((NOW_EPOCH-$(date +%s -d"$TIMESTAMP")))
    INDEX=$((INDEX+1))
    if [ "$FLAG" = "1" ]; then
      P_AGE_REF1=$((AGE_LAST-P_AGE_DEL))
      P_AGE_REF2=$((AGE_LAST*P_AGE_FRC/10))
      vecho 3 "D: update check rule"
    fi
    if [ "$INDEX" -gt "$INDEX_OLD" ]; then
      report "keep" "$TIMESTAMP" "AGE=$AGE, $(($#-INDEX))/${INDEX_NEW}-th newest (6)"
      FLAG=0 # don't bother
    elif [ "$AGE" -gt "$P_AGE_HI" ] && [ "$AGE" -gt "$P_AGE_REF1" ]; then
      report "delete" "$TIMESTAMP" "$AGE !< HI=$P_AGE_HI, DEL=$P_AGE_REF1, FRC=$P_AGE_REF2 (1)"
      FLAG=0
    elif [ "$AGE" -gt "$P_AGE_HI" ]; then
      report "keep" "$TIMESTAMP" "AGE=$AGE << HI=$P_AGE_HI, DEL=$P_AGE_REF1, FRC=$P_AGE_REF2 (2)"
      FLAG=1
    elif [ "$AGE" -lt "$P_AGE_LO" ]; then
      report "keep" "$TIMESTAMP" "AGE=$AGE << LO=$P_AGE_LO young (5)"
      FLAG=0 # don't bother
    elif [ "$AGE" -gt "$P_AGE_REF2" ]; then
      report "delete" "$TIMESTAMP" "AGE=$AGE !< FRC=$P_AGE_REF2 (3)"
      FLAG=0
    else
      report "keep" "$TIMESTAMP" "AGE=$AGE << FRC=$P_AGE_REF2 (4)"
      FLAG=1
    fi
    AGE_LAST="$AGE"
  done
  return
}

NOW_EPOCH=$(date -u +%s)
INDEX_NEW=5                  # Number of new timestamp index (last in list) to keep
P_AGE_HI=$((200*24*60*60))   # Use P_AGE_DEL to prune if old:   >> P_AGE_HI
P_AGE_LO=$((60*60))          # Keep always young ones if young: << P_AGE_LO
P_AGE_DEL=$((100*24*60*60))  # Prune delta criteria for old ones
P_AGE_FRC=7                  # Prune ratio criteria for typical ones (7 means 70%)

btrfs_snap_list () {
  P_MODE="both"
  # shellcheck disable=SC2046,SC2010
  prune $(cd "$BTRFS_SNAP" >/dev/null ; ls -1d -- * | \
    grep -E '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\+00:00$')
}

btrfs_snap_simulate () {
  P_MODE="delete"
  # shellcheck disable=SC2046,SC2010
  LIST=$(prune $(cd "$BTRFS_SNAP" >/dev/null ; ls -1d -- * | \
    grep -E '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\+00:00$') |\
    sed -e "s:^:$HOME/snap/:")
  for D in $LIST; do
    echo " $ sudo btrfs subvolume delete  $D"
  done
}

btrfs_snap_prune () {
  P_MODE="delete"
  # shellcheck disable=SC2046,SC2010
  LIST=$(prune $(cd "$BTRFS_SNAP" >/dev/null ; ls -1d -- * | \
    grep -E '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}\+00:00$') |\
    sed -e "s:^:$HOME/snap/:")
  for D in $LIST; do
    sudo btrfs subvolume delete  "$D"
  done
}

btrfs_snap_help () {
echo "NAME"
echo "    ${0##*/} -- btrfs backup helper"
echo
echo "SYNOPSIS"
echo "    ${0##*/} [-s|-x|-q|-v] [backup|list|prune|simu|help]"
echo
echo "DESCRIPTION"
echo "    -x        trace shell command for debug"
echo "    -q        quiet"
echo "    -v        verbose"
echo "    -vv       very verbose"
echo "    backup:   backup data in $BTRFS_SRC"
echo "    list:     list backed up data in $BTRFS_SNAP"
echo "    simu:     prune old backed up data in $BTRFS_SNAP (simulation)"
echo "    prune:    prune old backed up data in $BTRFS_SNAP"
echo
echo "Copyright 2020 Osamu Aoki <osamu@debian.org>, GPL 2+"
}

##############################################################################
# constants
##############################################################################
if [ -z "$*" ]; then
  btrfs_snap_help
  exit
fi
for x in "$@" ; do
  case $x in
    h*) btrfs_snap_help
      ;;
    b*)
      TIMESTAMP=$(date -u --iso=second)
      if [ -d "$HOME/snap/$TIMESTAMP" ]; then
        echo "Try this later"
        exit 0
      else
        sudo btrfs subvolume snapshot -r "$BTRFS_SRC" "$HOME/snap/$TIMESTAMP"
      fi
      ;;
    p*) btrfs_snap_prune
      ;;
    l*) btrfs_snap_list
      ;;
    s*) btrfs_snap_simulate
      ;;
    *) echo "Unknown command: '$x'"
      btrfs_snap_help
      exit
      ;;
  esac
  shift
done

