#!/bin/sh -e
# vim:se tw=78 ai ts=2 sts=2 et:
# check 2 directories
# $ hal cmpdir sourcedir targetdir

# Most basic check (difference only)
#diff -qNr "$1/" "$2/"

# Most basic check ($2/ missing identified)
#diff -qr --unidirectional-new-file "$1/" "$2/"

# With rsync (checksum)
rsync -nrvc --delete "$1/" "$2/"

# With rsync (timestamp)
#rsync -nrvu --delete "$1/" "$2/"
