#!/bin/bash -e
# vim:se tw=78 ai si ts=2 sts=2 sw=2 et:
#
# configutration
#
pre=$(echo ~)

# functions
f_help () {
  echo "Syntax:"
  echo "  hal conf i[nstall]"
  echo "  hal conf d[iff]"
  echo "  hal conf b[ackup]"
  echo "  hal conf u[pdate]"
  exit
}

f_diff () {
# install the latest system skel files
  for p in /etc/skel/.* ; do
    f=$(basename $p)
    if [ -f "$p" ]; then
      echo " $ diff -u ~$p  ~/$f"
      diff -u "$p" ~/"$f" || true
    else
      :
    fi
  done
# install the latest dot files
  for p in ~/bin/dot/.* ; do
    f=$(basename "$p")
    if [ -f "$p" ]; then
      echo " $ diff -u ~${p#${pre}}  ~/$f"
      diff -u "$p" ~/"$f" || true
    fi
  done
# install the latest pbuilder hooks
  sudo mkdir -p /var/cache/pbuilder/hooks
  for p in ~/bin/pbuilder/* ; do
    f=$(basename "$p")
    if [ -f "$p" ]; then
      echo " $ diff -u ~${p#${pre}}  .../hooks/$f"
      sudo diff -u "$p" "/var/cache/pbuilder/hooks/$f" || true
    fi
  done
}

f_install () {
# check diff
  f_diff
  echo "============================================================================"
# install the latest system skel files
  for p in /etc/skel/.* ; do
    f=$(basename $p)
    if [ -f $p ]; then
      echo " $ cp -f $p ~/$f"
      cp -f $p ~/$f
    fi
  done
# install the latest dot files
  for p in ~/bin/dot/.* ; do
    f=$(basename $p)
    if [ -f $p ]; then
      echo " $ cp -f ~${p#${pre}}  ~/$f"
      cp -f $p ~/$f
    fi
  done
# install the latest pbuilder hooks
  sudo mkdir -p /var/cache/pbuilder/hooks
  for p in ~/bin/pbuilder/* ; do
    f=$(basename $p)
    if [ -f $p ]; then
      echo " $ sudo cp -f ~${p#${pre}}  .../hooks/$f"
      sudo cp -p $p /var/cache/pbuilder/hooks/$f
    fi
  done
}

f_backup () {
  BUPATH="backup/BU$(date -u +'%Y%m%d%H%M')"
  echo "Back up to ~/$BUPATH"
  mkdir -p ~/$BUPATH/dot
  mkdir -p ~/$BUPATH/pbuilder/hooks
  mkdir -p ~/$BUPATH/.config/
  mkdir -p ~/$BUPATH/.local/share/
  mkdir -p ~/$BUPATH/.getmail/
  mkdir -p ~/$BUPATH/etc
  mkdir -p ~/$BUPATH/etc/ssh
  mkdir -p ~/$BUPATH/etc/sudoers.d
  mkdir -p ~/$BUPATH/etc/exim4
  mkdir -p ~/$BUPATH/backup
# backup the latest system skel files
  for p in /etc/skel/.* ; do
    f=$(basename $p)
    if [ -f "$p" ]; then
      echo " $ cp -f ~/$f  ~/$BUPATH/dot/$f"
      cp -f ~/"$f" ~/"$BUPATH/dot/$f"
    fi
  done
# backup the latest dot files
  for p in ~/bin/dot/.* ; do
    f=$(basename "$p")
    if [ -f "$p" ]; then
      echo " $ cp -f ~/$f  ~/$BUPATH/dot/$f"
      cp -f ~/"$f" ~/"$BUPATH/dot/$f"
    fi
  done
# backup the latest pbuilder hooks
  for p in ~/bin/pbuilder/* ; do
    f=$(basename "$p")
    if [ -f "$p" ]; then
      echo " $ sudo cp -f .../hooks/$f  ~/$BUPATH/pbuilder/hooks/$f"
      sudo cp -f "/var/cache/pbuilder/hooks/$f" ~/"$BUPATH/pbuilder/hooks/$f"
    fi
  done
  echo "===================================================================="
# Non-public data
# backup the latest ~/bin directory
  echo "backup from ~/bin directory"
  cp -a ~/bin/ ~/$BUPATH/
# backup the latest ~/.gnupg directory
  echo "backup from ~/.gnupg directory"
  cp -a ~/.gnupg/ ~/$BUPATH/
# backup the latest ~/.ssh directory
  echo "backup from ~/.ssh directory"
  cp -a ~/.ssh/ ~/$BUPATH/
# backup the latest ~/.config/evolution directory
  echo "backup from ~/.config/evolution directory"
  cp -a ~/.config/evolution/ ~/$BUPATH/.config/
# backup the latest ~/.local/evolution directory
  echo "backup from ~/.local/evolution directory"
  cp -a ~/.local/share/evolution/ ~/$BUPATH/.local/share/
# backup the latest ~/.getmail directory
  echo "backup from ~/.getmail directory"
  cp -a ~/.getmail/ ~/$BUPATH/
# backup the latest ~/.msmtprc file
  echo "backup from ~/.msmtprc file"
  cp -a ~/.msmtprc ~/$BUPATH/
# backup the latest /etc directory
  echo "backup from /etc directory"
  for f in aliases email-addresses debian_version fstab hostname hosts \
	  sysctl.conf sudoers group gshadow passwd shadow; do
    p="/etc/$f"
    if [ -f "$p" ]; then
      echo " $ sudo cp -f /etc/$f  ~/$BUPATH/etc/$f"
      sudo cp -f "/etc/$f" ~/"$BUPATH/etc/$f"
    fi
  done
  for p in /etc/sudoers.d/* ; do
    f=$(basename "$p")
    if [ -f "$p" ]; then
      echo " $ sudo cp -f /etc/sudoers.d/$f  ~/$BUPATH/etc/sudoers.d/$f"
      sudo cp -f "/etc/sudoers.d/$f" ~/"$BUPATH/etc/sudoers.d/$f"
    fi
  done
  for p in /etc/ssh/* ; do
    f=$(basename "$p")
    if [ -f "$p" ]; then
      echo " $ sudo cp -f /etc/ssh/$f  ~/$BUPATH/etc/ssh/$f"
      sudo cp -f "/etc/ssh/$f" ~/"$BUPATH/etc/ssh/$f"
    fi
  done
  for p in /etc/exim4/* ; do
    f=$(basename "$p")
    if [ -f "$p" ]; then
      echo " $ sudo cp -f /etc/exim4/$f  ~/$BUPATH/etc/exim4/$f"
      sudo cp -f "/etc/exim4/$f" ~/"$BUPATH/etc/exim4/$f"
    fi
  done
  echo " $ sudo tar --create -v -f ~/$BUPATH/backup/alternatives.tar -C /etc alternatives"
  sudo tar --create -v -f ~/"$BUPATH/backup/alternatives.tar" -C /etc alternatives
# backup the latest /var/lib directory
  for p in apt/extended_states aptitude/pkgstates dpkg/diversions \
	  dpkg/statoverride dpkg/status;  do
    f=$(basename "$p")
    d=$(dirname "$p")
    echo " $ sudo cp -f /var/lib/$d/$f  ~/$BUPATH/backup/$d.$f"
    sudo cp -f "/var/lib/$d/$f" ~/"$BUPATH/backup/$d.$f"
  done
  echo "===================================================================="
  echo "You need to do 'dpkg-reconfigure -plow exim4-config' later"
  echo "to update exim server"
}

f_update () {
# update the template files by the latest installed dot files
  for p in ~/bin/dot/.* ; do
    f=$(basename $p)
    if [ -f $p ]; then
      echo " $ cp -f ~/$f  ~${p#${pre}}"
      cp -f ~/$f $p
    fi
  done
# update the template files by the latest installed pbuilder hooks
  sudo mkdir -p /var/cache/pbuilder/hooks
  for p in ~/bin/pbuilder/* ; do
    f=$(basename $p)
    if [ -f $p ]; then
      echo " $ sudo cp -f .../hooks/$f ~${p#${pre}}"
      sudo cp -p /var/cache/pbuilder/hooks/$f $p
    fi
  done
}

case "$1" in
  b*)
    f_backup
        ;;
  i*)
    f_install
        ;;
  d*)
    f_diff
        ;;
  u*)
    f_update
        ;;
  *)
    f_help
esac
