#!/bin/bash -e
## @brief manage configuration files (public/private)
# vim:set tw=78 ai si ts=2 sts=2 sw=2 et:
#
# configuration
#
#HOME=$(echo ~)

#
# functions
f_help() {
  echo "Syntax:"
  echo "  hal ${0##*/} i[nstall] # install configuration files from git repo"
  echo "  hal ${0##*/} d[iff]    # diff configuration files against ones in git repo"
  echo "  hal ${0##*/} u[pdate]  # update git repo with installed configuration files"
  exit
}

f_diff() {
  echo
  echo "===== diff ====="
  echo
  echo "===== diff etc-skel-dot vs. installed-dot ====="
  for p in $(find /etc/skel -type f -o -type l); do
    # shellcheck disable=2001
    f=$(echo "$p" | sed -e "s,/etc/skel/,,")
    if [ -e "bin/dot/$f" ]; then
      echo " --- skip: ~/$f --- dot file exists in repo"
    elif [ -f "$p" ]; then
      echo " $ diff -u $p  ~/$f"
      diff -u "$p" "$f" || true
    else
      echo "***WARN***: missing dot file '~/$f'"
    fi
  done
  echo "===== diff repo-dot vs. installed-dot ====="
  # shellcheck disable=2231
  for p in $(find bin/dot -type f -o -type l); do
    # shellcheck disable=2001
    f=$(echo "$p" | sed -e "s,^bin/dot/,,")
    if [ -f "$f" ]; then
      echo " $ diff -u ~/$p  ~/$f"
      diff -u "$p" "$f" || true
    else
      echo "***WARN***: missing dot file '~/$f'"
    fi
  done
  echo "===== diff repo-etc vs. installed-etc ====="
  # shellcheck disable=2231
  for p in $(find bin/etc/ -type f -o -type l); do
    # shellcheck disable=2001
    f=$(echo "$p" | sed -e "s,^bin/etc/,/etc/,")
    if [ -f "$f" ]; then
      echo " $ diff -u $p $f"
      diff -u "$p" "$f" || true
    else
      echo "***WARN***: missing etc file '$f'"
    fi
  done
}

f_install() {
  # check diff
  f_diff
  echo
  echo "===== install ====="
  echo
  echo "===== install repo-dot files ====="
  # shellcheck disable=2231
  for p in $(find bin/dot -type f -o -type l); do
    # shellcheck disable=2001
    f=$(echo "$p" | sed -e "s,^bin/dot/,,")
    mkdir -p "${f%/*}"
    echo " $ cp -f -P ~/$p  ~/$f"
    cp -f -P "$p" "$f"
  done
  echo "===== install repo-etc files ====="
  # shellcheck disable=2231
  for p in $(find bin/etc/ -type f -o -type l); do
    # shellcheck disable=2001
    f=$(echo "$p" | sed -e "s,^bin/etc/,/etc/,")
    mkdir -p "${f%/*}"
    echo " $ cp -f -P ~/$p  $f"
    sudo cp -f -P "$p" "$f"
  done
}

f_update() {
  # check diff
  f_diff
  echo
  echo "===== update ====="
  echo
  echo "===== update repo-dot files ====="
  # shellcheck disable=2231
  for p in $(find bin/dot -type f -o -type l); do
    # shellcheck disable=2001
    f=$(echo "$p" | sed -e "s,^bin/dot/,,")
    mkdir -p "${p%/*}"
    echo " $ cp -f -P ~/$f  ~/$p"
    cp -f -P "$f" "$p"
  done
  echo "===== update repo-etc files ====="
  # shellcheck disable=2231
  for p in $(find bin/etc/ -type f -o -type l); do
    # shellcheck disable=2001
    f=$(echo "$p" | sed -e "s,^bin/etc/,/etc/,")
    mkdir -p "${p%/*}"
    echo " $ cp -f -P $f  ~/$p"
    sudo cp -f -P "$f" "$p"
  done
}

cd
echo "===== current directory = `pwd` ====="
case "$1" in
i*)
  f_install
  ;;
d*)
  f_diff
  ;;
u*)
  f_update
  ;;
*)
  f_help
  ;;
esac
