#!/bin/sh -e
# vim:se tw=78 ai ts=2 sts=2 et:
# install latest skeltons

if [ -n "$1" -a -z "${1%%i*}" ] ; then
  # start with "i"
  COMMAND=cp
elif [ -n "$1" -a -z "${1%%d*}" ] ; then
  # start with "d"
  COMMAND="diff -u"
elif [ -n "$1" -a -z "${1%%b*}" ] ; then
  # start with "b"
  COMMAND=":" # NOP
else
  echo "Syntax:"
  echo " $ hal dotfiles i[nstall]"
  echo " $ hal dotfiles d[iff]"
  echo " $ hal dotfiles b[ackup]"
  exit
fi

if [ "$COMMAND" = "diff -u" ] ; then
  echo "Addition of ~/.bashrc_local to ~/.bashrc is OK."
  echo
fi

for f in /etc/skel/.* ; do
  if [ -f $f ]; then
    $COMMAND $f ~/$(basename $f)
  fi
done

if [ "$COMMAND" = "cp" ] ; then
  echo "###### Extra entries as ~/.bashrc_local ######" >>~/.bashrc
  echo '[ -f ~/.bashrc_local ] && . ~/.bashrc_local' >>~/.bashrc
fi

# install latest dotfiles
for f in ~/bin/dotfiles/.* ; do
  if [ -f $f ]; then
    $COMMAND $f ~/$(basename $f)
  fi
done

if [ "$COMMAND" != ":" ] ; then
# install latest pbuilder files
  sudo mkdir -p /var/cache/pbuilder/hooks
  for f in ~/bin/pbuilder/* ; do
    if [ -f $f ]; then
      sudo $COMMAND $f /var/cache/pbuilder/hooks/$(basename $f)
    fi
  done
fi

if [ "$COMMAND" = ":" ] ; then
  BUPATH="backup_$(date -u +'%Y%m%d')"
  echo "Back up to $BUPATH"
  mkdir -p $BUPATH/home
  mkdir -p $BUPATH/etc
  cd $BUPATH/home >/dev/null
  echo "backup home directory"
  set -x
  cp -a ~/bin/          bin/
  cp -a ~/.getmail/     .getmail/
  cp -a ~/.gnupg/       .gnupg/
  cp -a ~/.ssh/         .ssh/
  cp -a ~/.bash_aliases .bash_aliases
  cp -a ~/.bashrc       .bashrc
  cp -a ~/.bashrc_local .bashrc_local
  cp -a ~/.mailfilter   .mailfilter
  cp -a ~/.msmtprc      .msmtprc
  cp -a ~/.muttrc       .muttrc
  cp -a ~/.profile      .profile
  cp -a ~/.vimrc        .vimrc
  set +x
  cd ../etc >/dev/null
  echo "backup /etc directory"
  set -x
  sudo cp -a /etc/exim4/passwd.client          exim4_passwd.client
  sudo cp -a /etc/exim4/update-exim4.conf.conf exim4-update-exim4.conf.conf
  sudo cp -a /etc/email-addresses              email-addresses
  set +x
  echo "===================================================================="
  echo "You need to do 'dpkg-reconfigure -plow exim4-config' later"
  echo "to update exim server"
fi
