#!/bin/sh
# vim:se tw=78 ai ts=2 sts=2 et:
# install latest skeltons

if [ -n "$1" -a -z "${1%%i*}" ] ; then
  # start with "i"
  COMMAND=cp
elif [ -n "$1" -a -z "${1%%d*}" ] ; then
  # start with "d"
  COMMAND="diff -u"
else
  echo "Syntax:"
  echo " $ hal dotfiles i[nstall]"
  echo " $ hal dotfiles d[iff]"
  exit
fi

if [ "$COMMAND" = "diff -u" ] ; then
  echo "Addition of ~/.bashrc_local to ~/.bashrc is OK."
  echo
fi

for f in /etc/skel/.* ; do
  if [ -f $f ]; then
    $COMMAND $f ~/$(basename $f)
  fi
done

if [ "$COMMAND" = "cp" ] ; then
  echo "###### Extra entries as ~/.bashrc_local ######" >>~/.bashrc
  echo '[ -f ~/.bashrc_local ] && . ~/.bashrc_local' >>~/.bashrc
fi
# install latest dotfiles
for f in ~/bin/dotfiles/.* ; do
  if [ -f $f ]; then
    $COMMAND $f ~/$(basename $f)
  fi
done

# install latest pbuilder files
sudo mkdir -p /var/cache/pbuilder/hooks
for f in ~/bin/pbuilder/* ; do
  if [ -f $f ]; then
    sudo $COMMAND $f /var/cache/pbuilder/hooks/$(basename $f)
  fi
done

