#!/bin/sh -e
## @brief print this help message
# vim:se sw=2 ts=2 sts=2 et ai tw=78:
# Local shell command family
THISPATH=$(realpath "$0")
THISDIR=$(dirname "${THISPATH}")

echo "wrapper command to keep clean namespace for shell commands"
echo
echo "Sub-command choices and meanings:"
cd "${THISDIR}" >/dev/null
for c in * ; do
  if [ "${#c}" -lt 7 ]; then
    b=$(sed -n -e '/^## @brief\s\s*/s/## @brief\s\s*/\t\t/p' "$c")
  else
    b=$(sed -n -e '/^## @brief\s\s*/s/## @brief\s\s*/\t/p' "$c")
  fi
  echo " $c$b"
done
