#!/bin/sh -e
## @brief initial system setups (apt/sudo/...)
# Initial setup
# Copyright 2018 Osamu Aoki <osamu@debian.org>, GPL-2+
# vim: set ts=2 sts=2 sw=2 ai et:
#############################################################################
# Set to run as ROOT
#############################################################################
SUDOERS="/etc/sudoers.d/passwordless"
if [ "$(id -un)" != root ]; then
  #set -x
  if [ -x /usr/bin/sudo ] && [ -r "$SUDOERS" ]; then
    echo "Please type the password of your user account"
    sudo --preserve-env "$0" "$@"
  else
    echo "Please type the password of the root account"
    su --preserve-environment -c "$0" "$@"
  fi
  #set +x
  exit
fi

echo "Executing '$0' (sub)command as root with '$*'" >&2

#############################################################################
# The following commands are run under ROOT
#############################################################################

#############################################################################
# initially we only have apt
#############################################################################
echo "I: step 0: install bare minimum"
apt update
apt install aptitude sudo
#############################################################################

#############################################################################
echo "I: set the primary user privileges (sudo) if not yet"
# Set primary user name (even if it was started as root)
#USERNAME=$(id -un 1000)
mkdir -p /etc/sudoers.d
if [ ! -f "$SUDOERS" ]; then
  cat >"$SUDOERS" <<END
# No passowrd required for the user in sudo group
# please note the last match wins configuration
%sudo ALL = (ALL:ALL) NOPASSWD: ALL
# No password for 8 hours
#Defaults timestamp_timeout = 480
#Defaults timestamp_type = global
END

  #############################################################################
  echo "set group membership"
  # Set up normal group membership
  # for admin work with sudo
  /usr/sbin/adduser "$USERNAME" sudo
  # To read and manupulate /var/sppol/mail/<username>
  /usr/sbin/adduser "$USERNAME" mail
  /usr/sbin/adduser "$USERNAME" adm
  /usr/sbin/adduser "$USERNAME" backup
  /usr/sbin/adduser "$USERNAME" dialout
  /usr/sbin/adduser "$USERNAME" dip
  /usr/sbin/adduser "$USERNAME" games
  /usr/sbin/adduser "$USERNAME" src
  /usr/sbin/adduser "$USERNAME" staff
  /usr/sbin/adduser "$USERNAME" www-data
fi
#############################################################################
echo "set grub installer to probe other drives"
if grep -q "^GRUB_DISABLE_OS_PROBER=false" /etc/default/grub; then
  echo "Already probing multiple drives"
elif grep -q "^#GRUB_DISABLE_OS_PROBER" /etc/default/grub; then
  echo "Already updated and set not to probe multiple drives"
else
  echo "Enable to probe multiple drives"
  echo "" >>/etc/default/grub
  echo "# Set up to probe other drives" >>/etc/default/grub
  echo "#GRUB_DISABLE_OS_PROBER=false" >>/etc/default/grub
fi
#############################################################################
echo "set apt/aptitude with all repo access"
#############################################################################
sed -i -e 's/main.*$/main non-free-firmware contrib non-free/' /etc/apt/sources.list

if grep -q "backports" /etc/apt/sources.list; then
  echo "Already backports enabled"
else
  echo "Enable backports"
  cp /etc/apt/sources.list /etc/apt/sources.list.orig
  echo >>/etc/apt/sources.list
  sed -n -e 's/, previously.*$/ from testing/' -e 's/-updates/-backports/gp' \
    /etc/apt/sources.list.orig >>/etc/apt/sources.list
fi
cat >"/etc/apt/sources.list.d/osamuaoki.sources" <<END
Types: deb
URIs: http://osamuaoki.github.io/debian/
Suites: sid
Components: main
Signed-By:
 -----BEGIN PGP PUBLIC KEY BLOCK-----
 Version: GnuPG v1.4.10 (GNU/Linux)
 . 
 mQINBEya74YBEADDpLTJCmyS97kZ6JvlpUEoSoVbqEkyQVfrV7C7VqlBGWO0bTKI
 z0QAOkzF47HIDTez+ISLRd84Dyh/BPpSTF2CP3HnLo21UxotvQFeVVs87EKTgrM5
 MsRgmEU4o28be0Uz0ix0U5ahaOqX6TI1+faZ8Bn2Q9MnhYoSaS0DyRrEAIU0xrSk
 VDrN3GrjUYli2GwF/GgKCKT92rxPvcaJIbtMqNWkm9QJVqyTLNw/kY1ywU5weehE
 tIK0IU2ib5dakYubUfdCv54UXAB30sryMpgbi60ELEtEG1t6icKBOta+kCHkDggl
 Ts9YIAOMQvRy1qwiySuv1P+4AOSoC7yS/WlGBoGOhThSnGcdjoXXGixmkeSw3MO5
 F/2e3vd7BWDDygyxJldtf8p6OmD6bj7FLoPB97Qvilpt2JQ27Sn9zVOC4/wCKaqx
 628GXsKx4gyoieSCKxHJuGTuD7nyAnqn/E04IyhJ5TAjai39x+ZUwWnT84dSOnEm
 0+3lORr9Iwkrbrom5BFZ9vrgEQ1Dp52v5anfjlPPiPdUMF/66H9nFrhjS26LLodA
 WUEWAoc4u2vjAOD2LGjCs1XKdVMgFci2rVLSVYlj2aWjU3dPUvqvGo0IReiJx9RY
 MEBZnc9CHEdWFZjVUFFKc/pjrgwIcq6LDRIPdd2n8bYy0y8TxFwyax9bPQARAQAB
 tB1Pc2FtdSBBb2tpIDxvc2FtdUBkZWJpYW4ub3JnPokCOAQTAQIAIgUCTJrvhgIb
 AwYLCQgHAwIGFQgCCQoLBBYCAwECHgECF4AACgkQHhNWiB3Y15FJNRAAuKkCIxJO
 3QrcscEPwS0n/gXBPYlAkxNMJOT3Iju8D7aweIjEeEm4YN8wZWNvqD1npkFHcDXl
 LlNpcsIoQOoyyT4XIJ2bC8z80pxGTUdNd/FcmmJi8QMrg8+xf/cGvA3FdM9vdWOQ
 lai5m5HyAdz/kvxD5KXw6GUOybzxVSg/MKK+Ugcwl/sHU9FT9zgy5myeNSiChn1J
 DntBsKh3TWQd3uXKdFS0vaMvDDm3HeSwXBcV0tT8tMuaxOu2gdxv0br+SoFytsN+
 PSjTTr8Tu6n/EkwMugUmXTqoNRS726nt4fVzbKYIQ9QEz2O8udC5PumHvTIOKcTn
 ExuMy+M9cZhr5q5YOIIST3A04PtT6oUA5yJPtlQMGpE2642CwebWpXAhz+STWVJ7
 9mziN9Spd1TQ7r5wAukvYSRalO67WeONzntyX9KEzL2397ExKvO8FBpSpzms0S2F
 34CrZW2MfhrbOb3gh9phUXRLd2anU6k3cTiAMnMmLK+j8y3PDV2AApfhtaHQ7PPB
 EYCvtsiDj28kpTX2gh9rqhJFG/vQbHBDQQvb8C4eoIYCIwVrZ8GGXZTz+CSLsTax
 auCjBlLpV1I3n7jAddpHE4nsAA6FkQK63jhQg+maiiIOmdEQa00P+0Re4txOqlJR
 Kyao3TFRmJY/Z4Qbl3bfDfmzNZ0lZRHGZ+KIRgQQEQIABgUCTJszvAAKCRDoD8TB
 qAYfMnzoAJkBk91lkUmhMRpeyPBndB5DS9FwHQCfYZqI+/t4NHO/V/G7e+yr3ppG
 2O+5Ag0ETJrvhgEQANuySzxnEDcSFToNbiGiotoRfCJvKdHjPWLke7Vji+ro4BR1
 51wSjhv7lsVIiGhEmIp/bRO8mY3rwgiG1RUNI8cqDlzI0PtYJrrhcmi3ppB5y3fr
 kJilFgQijhDHnTTId1d3ntwwzzBrAxh8Bvx7BNbD9cN6ChIUJ6B6ISQpgw7EKnOT
 fYYc+EA/EppYcNsXKgm77W7/PC5Ss1Q01EQ2O9GDQxiF8OEbJANSO4wExAWK5LN4
 Kuod4vt7hoGzgfKo1woviuephAUxnqqKhK/WG0YB/nPFdGLn+mYWomMTe4ayrCIs
 HxS70gIt36DUAA1SDCTp8Fb34s9AB6YYEK83g4NW09e/Czoxl3W8Kej1uPwt62MV
 xjc8HzQ3wPCriXbye5Lc74NARj+N6lort5CwyPRiy5iBaygZVOw+pBA4kRdi5sGU
 vbSZ4tTvtCHMcg1zpSHs/P/qSUGsO+wGm9nWCB4i4zsDZ9GlEpneqSVtWgXKEbTz
 ymC/Z0tvORAOvamCkt06nnsbJqNdI7g82oCL/rkKCxNG/675kPHJGw/f1GyWuJz/
 6U1Zv6QFpKzVID9Wj5+pow8uDLxywEWHXmFjMEfg8E0FO4UStCo+qsIUdd6jQHh/
 VuFsGPQS0lH1FnR+jYljyrxUFcUFlrVzG5YtDrXFILFbEVUkbKrGbsfYUU2BABEB
 AAGJAh8EGAECAAkFAkya74YCGwwACgkQHhNWiB3Y15HN0A//QAKmdXv7nuddbe0k
 Wb27779e0HXKpuhj9DyuKU7lXIMqSwtD+/yo4vbb1nGVnPO/+xTF6ecUjnDrEMe/
 Q2fqHbm3bglwlkii9flvwORjxxBfghdJipFuloL3C28VuQgx2kNeYtbvyLP6roZx
 R80c2+NQTHtkL2Ba2dtiptwsB4vKk+a0vi9g+MjbPknSkoZ6TbZVog7ia0HcbS+Q
 stfXCQUPi1ccKK9oNFVdTTBLamnq4Ts6TAPRmRt7y4ob2dBm4R0Hpb9qIhTsI0+Y
 KL7rtXHX2bFcMgg0OHz/Vn8LGT+euEgcZi9CQp8C6mrO+mFybBSWhndBra8NPTSY
 4iLYz/MlHq6vvtFsmeCpO2BpfI5vUSWltSI7whA5B2wAEJ6oEWHfdxvWSzRDQ+BO
 Rk6I4QQZpulQRqjHpeDSiMLCZHXqikdooYlQr2hin9CBKPECAqNdqVSYjooOJlyE
 YfRbz/hqsOcfqigqKKJx3vqKSxkta6bieHjRE+iyP1usPbzY4bLj4gMP/CpDC8+m
 kNmNluFKFRHmCu+Jzlg+lcYH1tVUqVYe9wlS6op6YDVVwPWT9vU3sviry81ADb25
 Dg8TBQz5UCZvF8iHEpTS7KcmWKLW8oNY2y9kyyQKjvp2s5m59LrAy3gunqEqMS3o
 xqPj8/NMvWK8mJoL07R52TxDk6k=
 =2eP9
 -----END PGP PUBLIC KEY BLOCK-----

# This is wrtten in DEB822-STYLE FORMAT as described in sources.list (5)
END

aptitude update
aptitude full-upgrade
aptitude install 00-min # sudo vim installed


#############################################################################
echo ""
echo "======================================================================="
echo "Current Debian distribution supported:"
sed -n -e "s/^deb\s.*\/\s/    /p" /etc/apt/sources.list
echo "======================================================================="
echo ""
read -p "Type 'RETURN'-key to reboot the system (otherwise ^C to stop here)." FOO
/usr/sbin/shutdown -r now
