#!/bin/sh -e
# Setup initial install
# Copyright 2017 Osamu Aoki <osamu@debian.org>, GPL-2+
# vim: set ts=2 sts=2 ai et:
#############################################################################
# Set to run as ROOT
if [ $(id -un) != root ]; then
  USERNAME=$(id -un)
  export USERNAME
  if [ -r /etc/sudoers.d/custom ]; then
    sudo "$0"
  else
    echo "Please type the root password"
    su -c "$0"
  fi
  exit
fi
#############################################################################
# The following commands are run under ROOT
# Basic apt set up after the install: Enable contrib + non-free
if grep -q non-free /etc/apt/sources.list || \
   grep -q contrib /etc/apt/sources.list ; then
  echo "Already contrib + non-free enabled"
else
  echo "Enable contrib + non-free"
  sed -i -e 's/main/main contrib non-free/' /etc/apt/sources.list
fi
echo "Debian distribution:"
sed -n -e "s/^deb\s.*\/\s/    /p" /etc/apt/sources.list
#############################################################################
# Update package apt list
apt update
# Install basic packages in case you skipped
apt install sudo aptitude locales-all firmware-linux\
    vim emacs vim-tiny- nano- \
    mc cryptsetup lvm2 ssh
echo "One-time sudo password system, enabled."
#############################################################################
# Set one-time sudo password for the user in all terminals
cat >/etc/sudoers.d/custom <<END
# No password for 8 hours
Defaults timestamp_timeout = 480
Defaults timestamp_type = global
# NO password for the primary user (disabled)
#$USERNAME ALL=NOPASSWD: ALL
END
#############################################################################
# Set up normal group membership
adduser $USERNAME sudo
adduser $USERNAME adm
adduser $USERNAME src
adduser $USERNAME staff
adduser $USERNAME games
echo "One-time sudo password system, enabled."
#############################################################################
echo -n "Full-Upgrade? (possibly large download!) "
read YN
YN="${YN:-y}"
if [ "$YN" = "y" ]; then
  # upgrade all the way
  apt full-upgrade
fi
