#!/bin/sh -e
# Setup packages with GUI
# Copyright 2017 Osamu Aoki <osamu@debian.org>, GPL-2+
# vim: set ts=2 sts=2 ai et:
#############################################################################
. /etc/os-release # get OS version
PKGS=""
#############################################################################
# Desktop tools
#############################################################################
# Spell checker
PKGS="$PKGS task-desktop"
# Japanese input method support for me
PKGS="$PKGS ibus-anthy fonts-vlgothic fonts-ipaexfont"
# Desktop extras
PKGS="$PKGS xdu meld" 
PKGS="$PKGS gnote nixnote2 rxvt tomboy-"
PKGS="$PKGS chromium"
if [ "$VERSION" != "9 (stretch)" ]; then
# Not available in released stretch
PKGS="$PKGS pepperflashplugin-nonfree"
fi
# temperature sensor
PKGS="$PKGS psensor" 

#############################################################################
# Development environment for me (basics - no TeX, gcc)
#############################################################################
PKGS="$PKGS devscripts debmake git-buildpackage ben time"
PKGS="$PKGS wget w3m xxd screen tmux rename signing-party"
PKGS="$PKGS git gitk quilt subversion grip git-annex dgit"
PKGS="$PKGS ccache eatmydata vim-addon-manager"
# Development environment for me (debug)
PKGS="$PKGS rlwrap lsof xtrace ltrace strace gdb moreutils"
# Perl REPL and readline 
PKGS="$PKGS libreply-perl libterm-readline-gnu-perl"
# 
PKGS="$PKGS imediff2"
# Info
PKGS="$PKGS texinfo pinfo"
PKGS="$PKGS texinfo-doc-nonfree"

#PKGS="$PKGS net-tools"

#############################################################################
# Install packages
#############################################################################
sudo apt update
sudo apt full-upgrade
sudo apt install $PKGS
