#!/bin/sh -e
#
# Prepare to execute jhead command for all files.
#
# I wrote this to accomodate easy ISO image conversion
#

# My samba directory has funny ownership, fix it.
sudo chown -R $UID .
find . -type f -exec chmod ugo=rw '{}' \;
find . -type d -exec chmod ugo=rwx '{}' \;
find . -type f \( -name 'ZbThumbnail.info' \
	    -o -name 'Thumbs.db' \
	    -o -iname 'TRANS.TBL' \
	    -o -iname '*.TMP' \) \
	    -exec rm '{}' \;
