#!/bin/sh -e
#
# For slow months, merge dayly folders to monthly folders.
mkdir -p BAG

# Move to BAG
find . -path ./BAG -prune -o -type f -iname '*.jpg' -exec mv '{}' ./BAG/ \;

# Remove daily dir.
for i in * ; do 
        if [ -d $i ] && [ "$i" != "BAG" ]; then
                rmdir $i || true
        fi
done

# Move to monthly dir
for i in ./BAG/*-*.jpg; do 
        if [ -f $i ]; then
        j=${i#./BAG/}
        k=${j:0:2}
        mkdir -p ${k} ; 
        mv $i ${k}/${j} ; 
        fi
done

rmdir BAG || true
