#!/bin/sh -e
## @brief print nvme ssd S.M.A.R.T. info
# vim:set tw=78 sts=2 ts=2 sw=2 et ai si:
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
  echo "print nvme ssd S.M.A.R.T. info

example: print Model and Temperature repeatedly

  \$  watch \"hal ${0##*/}|grep '^te\\|^Mo'\"

(For temperature, psensor does a good job.)
"
  exit
fi
for dev in /dev/nvme? ; do
  sudo smartctl -a "$dev" | grep \
    -e '^Model Number:' \
    -e '^Firmware Version:' \
    -e 'Comp. Temp. Threshold:' \
    -e '^SMART overall-health self-assessment test result:'
  sudo nvme smart-log "$dev"
  echo
done

