#!/bin/sh -e

bind_mount () {
  # @ $1  original system path (top)    -- seen after bind mount
  # @ $2  chroot system path (bottom)   -- hidden below (chroot FS)
  echo "bind_mount: $1 on $2"
  if [ ! -d "$1" ]; then
    echo "E: directory in original system missing: '$1'" >&2
    exit 1
  fi
  LUID="$(stat -c %u "$1")"
  LGID="$(stat -c %g "$1")"
  LMOD="$(stat -c %a "$1")"
  sudo mkdir -p "$2"
  sudo chown "$LUID:$LGID" "$2"
  sudo chmod "$LMOD" "$2"
  sudo mount --bind "$1" "$2"
}

bind_umount () {
  # @ $1  original system path (top)    -- seen after bind mount
  echo "bind_umount: $1"
  if [ -d "$1" ]; then
    sudo umount --lazy "$1"
  else
    echo "W: directory in original system missing: '$1'" >&2
  fi
}

##############################################################################
# alternative work environment
ALT="${1:-alt}"
MARKER=$HOME/.alternative
ALT_DIRS=".alternative/base .config/nvim .local/share/nvim .cache/nvim"
mkdir -p "$MARKER/base"
case $ALT in
  base|b)
    if [ -e "$MARKER/base/normal_path_hidden" ] ; then
      echo "I: in alt env = $(cat "$MARKER/base/normal_path_hidden")"
    else
      echo "I: *** NOT *** in alt env"
    fi
    exit 0
    ;;
  reset|r|unmount|un|u)
    if [ -e "$MARKER/base/normal_path_hidden" ] ; then
      echo "I: UN-mounting alt env = $(cat "$MARKER/base/normal_path_hidden")"
      ALT="$(cat "$MARKER/base/normal_path_hidden")"
      for d in $ALT_DIRS ; do
        bind_umount "$HOME/$d"
      done
      echo "I: finish UN-mounting"
    else
      echo "I: NOT in alt env"
    fi
    exit 0
    ;;
  status|''|?|??)
    if [ -e "$MARKER/base/normal_path_hidden" ] ; then
      echo "I: In alt env = $(cat "$MARKER/base/normal_path_hidden") -- status"
    else
      echo "I: NOT in alt env"
    fi
    exit 0
    ;;
esac
# $ALT is at least 3 chars
##############################################################################
echo "I: start set up alt env"
if [ -e "$MARKER/base/normal_path_hidden" ] ; then
  echo "I: Already alt env = $(cat "$MARKER/base/normal_path_hidden") running"
  echo "Run 'alt reset' to unmount first."
  exit 1
else
  mkdir -p "$MARKER/base-$ALT"
  echo "$ALT" > "$MARKER/base-$ALT/normal_path_hidden"

  echo "I: override some user configuration files from alternative path"
  for d in $ALT_DIRS ; do
    mkdir -p "$HOME/$d-$ALT"
    bind_mount "$HOME/$d-$ALT" "$HOME/$d"
  done
  echo "I: finish mounting"
fi

# vim:set ai et sw=2 ts=2 sts=2 tw=80:
