#!/bin/sh
#
# Backup to USB drive
#
# Sanity check
SUDO="sudo"
XUSER=$(id -u -n)
if [ ! -d /home/$XUSER/ ]; then
  echo "E: Home directory missing: /home/$XUSER/."
  exit 1
fi
if [ ! -d /media/$XUSER/ ]; then
  echo "E: Media directory missing: /media/$XUSER/."
  exit 1
fi
#
backup() {
  if [ -d /media/$XUSER/$1/ ]; then
    XDEVICE=$1
    XFOLDER=$2
    if [ -d /home/$XUSER/$XFOLDER/ ] &&
      [ -d /home/$XUSER/$XFOLDER/.bss.d/ ]; then
      if [ -d /media/$XUSER/$XDEVICE/ ] ; then
        echo "I: Found USB device $XDEVICE to store backup data."
        # check btrfs?
        if [ "$($SUDO stat -f -c %T "/media/$XUSER/$XDEVICE")" = "btrfs" ]; then
          if [ ! -d "/media/$XUSER/$XDEVICE/$XFOLDER" ]; then
            $SUDO btrfs subvolume create "/media/$XUSER/$XDEVICE/$XFOLDER"
            bss template "/media/$XUSER/$XDEVICE/$XFOLDER"
            $SUDO rm -f "/media/$XUSER/$XDEVICE/$XFOLDER/.bss.d/.bss.fltr"
          fi
          if [ -d /media/$XUSER/$XDEVICE/$XFOLDER/.bss.d/ ]; then
             echo "I: Start backup of $XFOLDER to $XDEVICE"
             bss copy /home/$XUSER/$XFOLDER/ /media/$XUSER/$XDEVICE/$XFOLDER
             echo "I: Start snapshot of $XFOLDER on $XDEVICE"
             bss snap /media/$XUSER/$XDEVICE/$XFOLDER
          else
            echo "E: Missing /media/$XUSER/$XDEVICE/$XFOLDER/.bss.d/"
            read -p "Type ENTER to skip or CTRL-C to stop" foo
          fi
        else
          echo "E: USB device /media/$XUSER/$XDEVICE/ is not btrfs"
          read -p "Type ENTER to skip or CTRL-C to stop" foo
        fi
      else
        echo "E: Missing USB device $XDEVICE to store backup data."
        read -p "Type ENTER to skip or CTRL-C to stop" foo
      fi
    else
      echo "E: Missing proper source data /home/$XUSER/$XFOLDER/ with .bss.d/"
      read -p "Type ENTER to skip or CTRL-C to stop" foo
    fi
  fi
}

echo "I: Backup started"
# Drive 1
backup USB_BKUP Documents
# Drive 2
backup BKUP_USB Documents

# BKUP_AV_2023 is full
#backup BKUP_AV_2023 Pictures
#backup BKUP_AV_2023 Music
echo "I: Backup end"
