#!/bin/bash -e
# vim:se ts=2 sts=2 et ai tw=78:
# Linux console key binding

# This uses BASHism

#sudo loadkeys /usr/share/keymaps/Caps2Ctrl.map

t=$(tempfile) || exit
trap "rm -f -- '$t'" EXIT
cat <<EOF >"$t"
keymaps 0-127
keycode 58 = Control        # CapsLock act as Ctrl
# keycode 29 = Caps_Lock    # Ctrl act as CapsLock
# alt_is_meta               # Fix the Alt key"
# Load this wth: sudo loadkeys /usr/share/keymaps/Caps2Ctrl.map
EOF
sudo loadkeys "$t"
trap - EXIT
exit

