#!/usr/bin/sh -e
# vim:se sw=2 ts=2 sts=2 et ai tw=128:
# convenience script to setup schroot
# Possible chroot users
# * /srv/chroot/${DIST}-amd64-sbuild for sbuild with minimum system
# * /srv/chroot/${DIST}-amd64-term for terminal shell prompt under schroot with loaded system

if [ "$(id -u)" != 0 ]; then
  exec sudo --preserve-env=DIST "$0" "$@"
fi
echo "I: executing as $(id -u -n) ..."
BASECHROOT="/srv/chroot"
ARCH="amd64"
DIST="${DIST:-unstable}"
PROFILE="osamu"
URL="http://127.0.0.1:3142/deb.debian.org/debian"
# create a minimum schroot for sbuild
echo "I: setting up DIST=${DIST} for sbuild ..."
DIRSCHROOT="${BASECHROOT}/${DIST}-${ARCH}-sbuild"
if [ -e "${DIRSCHROOT}" ]; then
  echo "E: ${DIRSCHROOT} exists"
  exit 1
fi
sbuild-createchroot --include=eatmydata,ccache  "${DIST}" "${DIRSCHROOT}" "${URL}"
# create additional chroot for use by terminal and X (No wayland?)
# $ xhost +si:localuser:osamu ; schroot -c chroot:${DIRTERM}-?? ; xhost -
echo "I: setting up DIST=${DIST} for term ..."
DIRTERM="${BASECHROOT}/${DIST}-${ARCH}-term"
if [ -e "${DIRTERM}" ]; then
  echo "E: ${DIRTERM} exists"
  exit 1
fi
cp -a --reflink=always  "${DIRSCHROOT}"  "${DIRTERM}"
# create schroot data entry /etc/schroot/chroot.d/${DIST}-${ARCH}-term
# while using schroot $PROFILE with uniq filename
cat > "/etc/schroot/chroot.d/${DIST}-${ARCH}-term-$$" <<EOF
[${DIST}-${ARCH}-term]
description=Debian ${DIST} ${ARCH} chroot for terminal with shared data
groups=root,sbuild
root-groups=root,sbuild
source-groups=root,sbuild
source-root-groups=root,sbuild
profile=${PROFILE}
type=directory
preserve-environment=true
directory=/srv/chroot/${DIST}-${ARCH}-term
union-type=overlay
command-prefix=eatmydata
EOF

