#!/bin/sh -e
# Split changes on a file into multiple git commits
#############################################################################
# Copyright (c) 2017 Osamu Aoki
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#############################################################################

help() {
    echo "update po

Usage: ${0##*/} <path> [<tag>]
                        <tag> default to HEAD"
}

if [ "$1" = "--help" ]; then
    help
    exit
fi

p=$1
shift
t=$1
if [ -z "$t" ]; then
    t="HEAD"
fi
echo "PO to update: $p"
echo "Base PO tag:  $t"
mv -f $p $p.my
git checkout $t -- $p
mv -f $p $p.their
msgcat --use-first $p.my $p.their > $p
# vim:se tw=78 ai sts=4 et:
