#!/bin/sh -e
# vim:se sw=2 ts=2 sts=2 et ai tw=78:
if [ -z "$1" ]; then
  echo "Syntax: ${$0##*/} <tag> [-m <message>]"
  exit
fi

TAG="$1"
shift

GIT_COMMITTER_DATE="$(git log -1 --format=%aD "$TAG")"
export GIT_COMMITTER_DATE
GIT_COMMIT_HASH="$(git log -1 --format=%H "$TAG")"
git tag -d "$TAG"
git tag -s "$@" "$TAG" "$GIT_COMMIT_HASH"
unset GIT_COMMITTER_DATE
