#!/bin/sh
# Clean git repository
#############################################################################
# Copyright (c) 2015 Osamu Aoki
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#############################################################################
# Find directory having .git
GITROOT=$(pwd)
while [ ! -d "${GITROOT}/.git" -a "${GITROOT}" != "/" ]; do
  GITROOT=$(readlink -e "${GITROOT}/..")
done
echo "Current directory:  $(pwd)"
echo "Git repo directory: ${GITROOT}"
case $GITROOT in
  /)
    echo "Skip -- no .git directory found in the parent directories."
    ;;
  /etc | /var | /opt | /srv | ${HOME}) # blacklist
    echo "Skip -- $GITROOT is a blacklisted directory."
    ;;
  ${HOME}/*) # whitelist
    if [ "$(pwd)" != "${GITROOT}" ]; then
      read -p "Are you sure? Type RETURN to clean everything:" x
    fi
    # there maybe autocrlf related diff in cached data
    git rm --cached -r .
    # normal reset
    git reset --hard HEAD
    git clean -d -f -x
    # there maybe submodule
    git submodule update --init --recursive
    ;;
  /media/* | /mnt/*) # almost_whitelist
    read -p "Are you sure? Type RETURN to clean everything:" x
    if [ "$(pwd)" != "${GITROOT}" ]; then
      read -p "Are you really sure? Type RETURN to clean everything:" x
    fi
    # there maybe autocrlf related diff in cached data
    git rm --cached -r .
    # normal reset
    git reset --hard HEAD
    git clean -d -f -x
    # there maybe submodule
    git submodule update --init --recursive
    ;;
  *)
    echo 'Skip "git zap" since you are in a wrong directory.'
    echo
    echo "If you really wish to do, run the following command manually."
    echo " \$ cd $GITROOT"
    echo ' $ git reset --hard HEAD'
    echo ' $ git clean -d -f -x'
    ;;
esac

# vim:se sw=2 tw=78 ai si et:
