#!/usr/bin/python3
# vim:se tw=0 sts=4 ts=4 et ai:
# python is used not to worry about dash/bash/ksh/zsh differences,
"""
git-unsquash: Un-squash a git commit for each file

Copyright © 2019 Osamu Aoki
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

import sys
from subprocess import *
import csv

MIN_PYTHON = (3, 5)
if sys.version_info < MIN_PYTHON:
    sys.exit("Python %s.%s or later is required.\n" % MIN_PYTHON)

msg_sub = (
    run(["git", "show", "-s", "--format=%s", "HEAD"], stdout=PIPE)
    .stdout.decode("utf8")
    .rstrip()
)

msg_bdy = run(["git", "show", "-s", "--format=%b", "HEAD"], stdout=PIPE).stdout.decode(
    "utf8"
)

head_org = run(["git", "rev-parse", "HEAD"], stdout=PIPE).stdout.decode("utf8").rstrip()

# git diff-tree --find-copies-harder -C10 --no-commit-id --name-status -r HEAD
diff_stat = run(
    [
        "git",
        "diff-tree",
        "--find-copies-harder",
        "-C10",
        "--no-commit-id",
        "--name-status",
        "-r",
        head_org,
    ],
    stdout=PIPE,
).stdout

run(["git", "reset", "HEAD^"])
file0 = ""
i = 0
for row in csv.reader(diff_stat, delimiter="\t"):
    if row[0][0] == "D":
        run(["git", "rm", "-f", row[1]])
        run(
            [
                "git",
                "commit",
                "--allow-empty",
                "-m",
                msg_sub + " #D{}\n\n".format(i) + msg_bdy,
            ]
        )
    elif row[0][0] == "A" or row[0][0] == "M":
        i += 1
        run(["git", "add", row[1]])
        run(
            [
                "git",
                "commit",
                "--allow-empty",
                "-m",
                msg_sub + " #A{}\n\n".format(i) + msg_bdy,
            ]
        )
    elif row[0][0] == "C" or row[0][0] == "R":
        run(["git", "add", row[2]])
        if row[0][0] == "R":
            run(["git", "rm", "-f", row[1]])
        if file0 == row[1]:
            # make sure to commit together with previous one
            run(
                [
                    "git",
                    "commit",
                    "--allow-empty",
                    "--amend",
                    "-m",
                    msg_sub + " #A{}\n\n".format(i) + msg_bdy,
                ]
            )
        else:
            i += 1
            run(
                [
                    "git",
                    "commit",
                    "--allow-empty",
                    "-m",
                    msg_sub + " #A{}\n\n".format(i) + msg_bdy,
                ]
            )
    else:
        print("STRANGE row")
        print(row)
        exit(1)
    file0 = row[1]
