#!/bin/sh -e
# vim:se sw=2 ts=2 sts=2 et ai tw=78:
# Local shell command family
THISPATH=$(realpath $0)
THISDIR=$(dirname ${THISPATH})
SUBCOMMAND="${1}"
# execute private subcommand in ./hal
if [ -n "$SUBCOMMAND" ] && [ -x "${THISDIR}/halexec/$SUBCOMMAND" ]; then
  shift
  "${THISDIR}/halexec/$SUBCOMMAND" "$@"
else
  echo "Sub-command '$SUBCOMMAND' not found."
  hal help
fi
