#!/bin/sh -e
# "lhugo" for localhost-hugo.git
cd ~/Documents/notes
DIR_NOTES=$(pwd)
killall hugo || true
systemd-cat -t hugo -p 6 hugo server -p 8080 --disableFastRender &
open http://localhost:8080/ > /dev/null 2>&1
gnome-terminal -- mc "$DIR_NOTES/content" "$DIR_NOTES"
# No shell alias work here
gnome-terminal -- nvim "$DIR_NOTES/content/memo.md"
