#!/bin/sh -e
# vim:se sw=2 ts=2 sts=2 et ai tw=78:
#
#
KEEP="0"
if [ "$1" = "-k" ]; then
  KEEP="1"
  shift
fi
PATH_DISK=$(realpath "${1:-disk.img}")
SIZE_DISK="${2:-8G}"
UID_DISK="${3:-1000:1000}"
DM_TARGET="${PATH_DISK##*/}"
DM_TARGET="${DM_TARGET%%.*}"
PATH_MNT=/mnt
echo "I: create image: $PATH_DISK" >&2
fallocate -l $SIZE_DISK $PATH_DISK
echo "I: create LUKS" >&2
cryptsetup luksFormat $PATH_DISK
echo "I: record passphrase for LUKS: $PATH_DISK" >&2
secret-tool store --label="LUKS $PATH_DISK" LUKS $PATH_DISK
secret-tool lookup LUKS $PATH_DISK | \
  sudo cryptsetup open $PATH_DISK $DM_TARGET --type luks
sudo mkfs.btrfs /dev/mapper/$DM_TARGET
mkdir -p $PATH_MNT
sudo mount /dev/mapper/$DM_TARGET $PATH_MNT
sudo chown 1000:1000 $PATH_MNT
if [ "$KEEP" != "1" ]; then
  sudo umount $PATH_MNT
  sudo cryptsetup close $DM_TARGET
fi
