#!/bin/sh -e
# vim:se tw=78 ai sts=2 et:
#
# This add git commit after UTF-8
tag=$1
for f in $(find . -path ./.git -prune -o -type f -print ); do
  nkf -w $f |sponge $f
done
git add -A .
git commit -m "commit $tag in utf8

This is for ease of code inspection under UTF-8.
The code probably doesn't function as intended.
"


