#!/bin/sh -e
# vim:se sw=2 ts=2 sts=2 et ai tw=78:
#
HOME="$(getent passwd "$(id -u)"|cut -d':' -f 6)"
# disk image path
PATH_DISK=$HOME/rsync/secret.img
# device mapper target name
DM_TARGET=secret
# mount path
PATH_MNT=$HOME/secret
# Create diskimage using luks-image script
if [ ! -e "$PATH_DISK" ]; then
  echo "disk image missing"
  exit 1
fi
if [ ! -e "$PATH_MNT" ]; then
  echo "mount point path missing"
  exit 1
fi
# wait for 120s
sleep 120
# let's mount
if mount|grep -e "$PATH_MNT" >/dev/null; then
  systemd-cat -p 5 -t "bss" \
    echo "skipping to mount LUKS disk image $PATH_DISK on $PATH_MNT (already mounted)"
else
  systemd-cat -p 5 -t "bss" \
    echo "mounting LUKS disk image $PATH_DISK on $PATH_MNT"
  secret-tool lookup LUKS "$PATH_DISK" | \
    sudo cryptsetup open "$PATH_DISK" "$DM_TARGET" --type luks
  sudo mount "/dev/mapper/$DM_TARGET" "$PATH_MNT"
  systemd-cat -p 5 -t "bss" echo "mounted $PATH_MNT"
fi
