#!/bin/sh -e
#
# Execute this command for all files and organize them
# on recovered data from cd
#
echo -n "You will be cleaning data in $(pwd).  Are you sure (y/n)?"
read YN
if [ "x$YN" = "xY" -o "x$YN" = "xy" ]; then
  echo "OK, cleaning..."
else
  exit 1
fi

# chown/chmod data (they may be copied from CDROM/samba/...)
sudo chown -R 1000:1000 .
chmod -R ugo+rwX .

# remove generated reduced size data in particular directories
find ./ -depth -type d \
            \( \
	    -regex '.*\/medium' \
	    -o -regex '.*\/thumbnail' \
	    -o -regex '.*\/slides' \
            \) \
	    -exec rm -rf '{}' \;

# remove generated index files created by many programs
find ./ -type f \
            \( \
	       -iname 'ZbThumbnail.info' \
	    -o -iname 'Thumbs.db' \
	    -o -iname 'TRANS.TBL' \
	    -o -iname '*.TMP' \
	    -o -iname '._*.jpg' \
	    -o -iname '*.css' \
	    -o -iname '*.html' \
	    -o -iname '*.xml' \
	    -o -iname '.DS_Store' \
	    -o -iname '._.DS_Store' \
            \) \
	    -exec rm -f '{}' \;

find . -type d -empty -delete


