#!/bin/sh
## @brief compare debian package version strings
#############################################################################
# Copyright (c) 2015 Osamu Aoki
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#############################################################################

V1=$1
V2=$2
if [ "$2" = "" ]; then
  echo "Syntax: hal ${0##*/} ver1 ver2"
elif dpkg --force-bad-version --compare-versions "$V1" gt "$V2"; then
  echo "$V1 >> $V2"
elif dpkg --force-bad-version --compare-versions "$V1" lt "$V2"; then
  echo "$V1 << $V2"
else
  echo "$V1 == $V2"
fi
# vim:se tw=78 ai sts=4 et:
