#!/bin/bash
## @brief make ISO image file of the target directory
# vim: set ts=2 sts=2 sw=2 ai et:
date=$(date --utc +"%Y%m%d")
if [ -d "$1" ]; then
  mkisofs -v -r -T -J -V "BU$date" -o dvd.img "$1"
else
  echo '... please provide the target directory as argument'
fi
