#!/bin/sh
#set -e
#set -x
# increase the ccache caching size
#ccache -M 4G
# output the current statistics
#ccache -s
# permissive
#chown -R 1234:1234 /var/cache/pbuilder/ccache
#chmod -R g+s,a+X,ug+w /var/cache/pbuilder/ccache
