#!/bin/sh
set -e
install_packages() {
    apt-get -y install $@
    }
install_packages lintian
echo "+++ lintian output +++"
#su -c "lintian -i -I --show-overrides /tmp/buildd/*.changes" -l pbuilder
# use this version if you don't want lintian to fail the build
su -c "lintian -i -I --show-overrides /tmp/buildd/*.changes; :" -l pbuilder
echo "+++ end of lintian output +++"
