#!/bin/sh -e
# vim:se ts=4 sts=4 et ai sw=4:
# Copyright (c) 2020 Osamu Aoki <osamu@debian.org>
# This code is hereby licensed for public consumption under either the
# GNU GPL v2 or greater.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

## @brief post-processing of *.m4a files to find missing track performer
#============================================================================
# Post-processing of *.m4a files ripped with "abcde -N -o m4a"
#
# * Find missing track performer
#============================================================================
if [ "$1" = "--noop" ] || [ "$1" = "-n" ]; then
    MODIFY=0
    shift
else
    MODIFY=1
fi

unknown_null ()
{
    echo "$1" | \
    sed -e 's/^Unknown.*$//' -e 's/^\[unknown\]$//'
}


for d in "$@"; do
    if [ ! -d "$d" ]; then
        continue
    fi
    OLDIFS="$IFS"
    # sh equivalent of $'\n'
    IFS='
'
    (
        cd "$d" >/dev/null
        # PASS #1: Analyze data
        for f in $(ls -1 -- *.m4a 2>/dev/null|| true) ; do
            ALBUM_PERFORMER=$(mediainfo --Inform="General;%Album/Performer%" "$f")
            ALBUM_PERFORMER="$(unknown_null "$ALBUM_PERFORMER")"
            TRACK_PERFORMER=$(mediainfo --Inform="General;%Performer%" "$f")
            TRACK_PERFORMER="$(unknown_null "$TRACK_PERFORMER")"
            if [ -z "$TRACK_PERFORMER" ] && [ -n "$ALBUM_PERFORMER" ] ; then
                if [ "$MODIFY" = 1 ]; then
                    AtomicParsley "$f" -W --artist "$ALBUM_PERFORMER"
                fi
                echo " ... $d/$f updated"
            fi
        done
    )
    IFS="$OLDIFS"
done
