#!/bin/sh -e
# vim:se sw=2 ts=2 sts=2 et ai tw=78:
reset
echo "I: remove old chroot"
sudo rm  -rf /srv/chroot/unstable-amd64-desktop
echo "I: remove old schroot"
sudo rm  -rf /etc/schroot/chroot.d/unstable-amd64-desktop-*
echo "I: schroot-shell -i"
schroot-shell -i
