#!/bin/sh
# vim:se tw=78 ai ts=2 sts=2 expandtab:
# Since we can not use 2 ids with:
# $CONFIG{'keyid'}       = [ qw{1E1356881DD8D791 E80FC4C1A8061F32} ];
# this script helps
# $@ is list of Key fingerprint

for ID in "$@" ; do
  echo "Process = $ID"
  echo "===  NEW KEY 1E1356881DD8D791 ==="
  caff -u 1E1356881DD8D791 $ID
  echo "===  OLD KEY E80FC4C1A8061F32 ==="
  caff -u E80FC4C1A8061F32 $ID
done

