#!/bin/sh -e
# Edit while commiting each exit to git repository
#############################################################################
# Copyright (c) 2015 Osamu Aoki
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#############################################################################

if [ ! -x /usr/bin/vim ]; then
    echo "Install the vim package."
    exit 1
fi
if [ "$1" = "-p" ];then
    PODMAKE="YES"
    shift
else
    PODMAKE="NO"
fi

if [ ! -r "$1" ]; then
    echo "Can not find <path>: $1" >&2
    help
    exit 1
fi
if [ -z "${1%%/*}" ]; then
    FILENAME="$1"
else
    FILENAME="`pwd`/$1"
fi
shift
COMMENT="${FILENAME##*/}: $@"
help() {
    echo "partial modification commit series

Usage: ${0##*/} [-p] <path> <comment>"
}

restore() {
:
}

trap restore EXIT HUP INT QUIT BUS USR1 PIPE TERM
# see "kill -l", signal(7)
# +  0 EXIT: on exit
# *  1 HUP:  hang-up (^\)
# *  2 INT:  KB interrupt (^C)
#    3 QUIT: QUIT (^D)
#    7 BUS:  buffer overflow etc.
#   10 USR1: user defined
# * 13 PIPE: broken pipe
# * 15 TERM: trappable termination
# No trap for KILL(9)

if ! git diff --exit-code $FILENAME ; then
    echo "Local changes. Erase them? (^C to quit)"
    read BOGUS
    git zap
fi

vim $FILENAME

git add $FILENAME

git commit $FILENAME -m "$COMMENT"

if [ "$PODMAKE" = "YES" ]; then
    if [ "${FILENAME%.pl}" = "${FILENAME%.*}.pl" ]; then
        pod2html $FILENAME >${FILENAME%%.pl}.html
        pod2man --utf8 --center=" " --release="Test" $FILENAME > ${FILENAME%%.pl}.1
    fi
fi

# vim:se tw=78 ai sts=4 et:
